### PR TITLE
Properly support fuel times greater than 32,767

### LINKED ISSUE #162: Fuel time improperly limited to a short
Offending line: https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/api/ItemContentRegistries.java#L51

Despite the fuel time REA being specced to an integer, it uses a short codec limitation, causing any mods who use an *ostensibly valid* fuel time of 32768 or higher to crash the game from an `IllegalArgumentException`. This should be remedied by switching to an int codec instead.

### PR DESCRIPTION
**Pull request by LemmaEOF**
Closes #162 by changing `Short.MAX_VALUE` to `Integer.MAX_VALUE`. Also patches furnaces to read and write `burnTime` as a Short instead of an int - this should have full compatibility with Vanilla clients due to all BEs being synced as their NBT-serialized forms nowadays.

**WARNING: I AM NOT ABLE TO TEST THIS ON MY COMPUTER, IT THEORETICALLY SHOULD WORK BUT I HAVE NO WAY TO VERIFY, PLEASE TEST AND ENSURE THIS DOESN'T CAUSE DESYNCS WITH VANILLA CLIENTS BEFORE MERGING**

### CODE REVIEW

**Comment by LemmaEOF** [comment]
Converting to draft - this PR will also end up mixing into furnace serialization to use ints instead of shorts to avoid the source of all this!

**Comment by LemmaEOF** [comment]
...I put the new stuff on the wrong branch in my fork lol, fixed now

**Review by OroArmor — APPROVED** [review]

**Review by EnnuiL — APPROVED** [review]
Once tested, I believe we're ready for a FCP

File: library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java [hunk 1]
```diff
@@ -18,7 +18,9 @@
 
 import java.util.Map;
 
+import net.minecraft.nbt.NbtCompound;
```
Comment (triphora) [inline library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java:21]: Definitely a checkstyle failure

File: library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java [hunk 2]
```diff
@@ -46,4 +51,17 @@ private static void collectInitialTags(Map<Item, Integer> fuelTimes, TagKey<Item
 			ci.cancel();
 		}
 	}
+
+	//Serializes burn time as an integer instead of a short
+	//Should not cause any desyncs as BE sync packets are now NBT
```
Comment (triphora) [inline library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java:56]: Probably a checkstyle failure

File: library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java (hunk 1 above)
Comment (EnnuiL) [reply library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java:21]: This is QSL, there are a heckton of checkstyle failures everywhere anyway

**Comment by EnnuiL** [comment]
By the way, I've tested this PR on a Vanilla client in a QSL server (a LAN server, more specifically); There are no serious issues on there, only visual weirdness on the client-side that shouldn't interfere on anything.

**Review by Leo40Git — APPROVED** [review]
LIMITS BROKEN
LGTM!

**Review by Platymemo — APPROVED** [review]

File: library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java (hunk 1 above)
Comment (LambdAurora) [reply library/item/item_content_registry/src/main/java/org/quiltmc/qsl/item/content/registry/mixin/AbstractFurnaceBlockEntityMixin.java:21]: I usually reformat on merge tbh
